export const REQUEST_POSTS = 'REQUEST_POSTS'
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS'
export const REQUEST_POSTS_FAILED = 'REQUEST_POSTS_FAILED'

export const REQUEST_POST = 'REQUEST_POST'
export const REQUEST_POST_SUCCESS = 'REQUEST_POST_SUCCESS'
export const REQUEST_POST_FAILED = 'REQUEST_POST_FAILED'

export const SET_TABLE_PAGE = 'SET_TABLE_PAGE'
export const SET_TABLE_ROWS_PER_PAGE = 'SET_TABLE_ROWS_PER_PAGE'
export const CHANGE_TABLE_PAGE = 'CHANGE_TABLE_PAGE'
